### ISSUE TITLE
双卡登录问题

### ISSUE THREAD

**Issue by BNDou** [zhinianboke/jd_ck_refresh#10]
佬，您做的app是否支持双卡都登陆？

因为我只收到一条短信，而且看到pro的log里面显示只提交了一次短信，咨询下另一张卡该如何登录？

**Comment by zhinianboke** [comment]
> 佬，您做的app是否支持双卡都登陆？
> 
> 因为我只收到一条短信，而且看到pro的log里面显示只提交了一次短信，咨询下另一张卡该如何登录？

软件可以支持输入2个手机号的吧，把两个手机号都填上就行了

**Comment by BNDou** [comment]
找到原因了，手机号1对应的我2号卡槽，手机号2对应的1号卡槽，我填反了😃

**Comment by zhinianboke** [comment]
> 找到原因了，手机号1对应的我2号卡槽，手机号2对应的1号卡槽，我填反了😃

能用就行，不过貌似填反了也不影响
