### ISSUE TITLE
车头格式相关疑问

### ISSUE THREAD

**Issue by BNDou** [zhinianboke/jd_ck_refresh#9]
佬，自定义车头格式是什么样的？

- 是不是需要带http协议头

- 域名后面加端口号能否识别

我这里运行提示 `服务器异常，请重试Unable to parse TLS packet header`

**Comment by zhinianboke** [comment]
> 佬，自定义车头格式是什么样的？
> 
> * 是不是需要带http协议头
> * 域名后面加端口号能否识别
> 
> 我这里运行提示 `服务器异常，请重试Unable to parse TLS packet header`

需要是pro程序才可以，加端口应该是支持的，不需要带http协议，需要开了ssl

**Comment by BNDou** [comment]
好的，那我知道原因了，我没有部署ssl证书😄
感谢！

**Comment by zhinianboke** [comment]
> 好的，那我知道原因了，我没有部署ssl证书😄 感谢！

建议下载最新版，可以保存自定义地址，防止软件下次打开自定义地址丢失

**Comment by BNDou** [comment]
谢谢👌🏻我先研究下ssl怎么整，我这儿不是云服务器，但是有公网ip
